kind: pipeline
name: cicd-demo

trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: tjdals5814/DevOps-YSM
    tags: latest
