kind: pipeline
type: docker
name: add-server-ci

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
  - master
  event:
    include:
    - push
    - pull_request
    - custom

steps:
- name: build-image
  <<: *x-build-docker-image
  settings:
    repo: tjdals5814/nginx
    dockerfile: Dockerfile
- name: deploy
  pull: always
  image: tjdals5814/cicd-demo-deploy:v1
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    IMAGE: tjdals5814/nginx
    VERSION: ${DRONE_COMMIT_SHA}
    REPO: DevOps-YSM
  depends_on:
    - build-image
