kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.16.10b7
  commands:
  - make DRONE_TAG=${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock
