kind: pipeline
type: docker
name: add-server-ci

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request

steps:
- name: build-image
  <<: *x-build-docker-image
  settings:
    repo: tjdals5814/DevOps-YSM
    dockerfile: Dockerfile
