kind: pipeline
name: default

steps:
- name: deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server: https://kubernetes.company.org
    kubernetes_token: CXHVLJSDKJFS...
    namespace: app
    deployment: my-deployment
    repo: myorg/myrepo
    container: my-container
    tag: mytag
