kind: pipeline
name: cicd-demo

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: tjdals5814/DevOps-YSM
    tags: latest
    
trigger:
  ref:
  - "refs/heads/master"
  event:
  - push
  - pull_request
  - custom
